### PR TITLE
Add support for logical types

### PR DESCRIPTION
**Pull request by olib963**
Adds support for:
* Timestamp-millis as `java.time.Instant`
* Time-millis as `java.time.LocalTime`
* Date as `java.time.LocalDate`
* UUID as `java.util.UUID`
* Decimal as `java.math.BigDecimal`, also an implementation that automatically sets the scale and rounds according to the mode given.
* Adding your own conversions/overloading defaults by passing e.g. `(datum-writer schema (merge c/default-conversions {:decimal (c/decimal-conversion-rounded :half-up)}))`

Keywords to be (de)serialised to/from strings by adding the `clojureType` prop i.e. `{"type":"sting", "clojureType":"keyword"}`

Tackles https://github.com/damballa/abracad/issues/29. I did originally implement an extensible version that allowed custom logical types and conversions. To be honest it was difficult to work with so I refactored to a simpler solution under the assumption it uses most of the types people want to use and we can make it extensible in the future if needed.

### CODE REVIEW

**Comment by iku000888** [comment]
This is great and long awaited! Cheers from me :)

**Comment by llasram** [comment]
So I'm not sure if @robbieh is going to chime in or not, but I don't believe anyone who currently has commit access to this repository is actively using Clojure for new development, or is even really maintaining these projects.  The company to which which this Github organization "belongs" hasn't existed for three(?) years.  And has a code-base which is mostly stuck on Clojure 1.6 forever due to none of us being able to find all the places CLJ-1738 wrought havoc.

Abracad in particular of the Damballa open source Clojure projects still seems to be actively used and in need of a maintainer.  It seems that one could do worse than soliciting new maintainers as part of the discussion on what is clearly a significant chunk of work on the project.  Assuming @robbieh agrees, @olib963, would you be interested in taking over this project?  Any other potential volunteers paying attention here?

**Comment by olib963** [comment]
I would be happy to look into that if this repo is no longer maintained, it seems like this would be a useful tool to keep up to date.

**Comment by olib963** [comment]
@iku000888 I have published https://github.com/ovotech/abracad to clojars. I will probably look at maintaining that one instead because then it isn't just me :P

**Pull request closed without merging**
