### PR TITLE
Fixed bug in "avro-record?"

### PR DESCRIPTION
**Pull request by stefanbacon**
Should check if datum has all fields of record not opposite else incompete datum can match

### CODE REVIEW

**Comment by stefanbacon** [comment]
Actually that's still not good if there is fields with type union with a :null

Maybe best to use the java API to resolve avro union ?

**Comment by stefanbacon** [comment]
nevermind please ignore this original code probably works for resolving union but not to be used for datum validation

**Comment by llasram** [comment]
Well it is somewhat for validation, but yeah -- not intended as a public API (the whole namespace is `:private`), and that function is just part of union-resolution.  The goal is to avoid silently ignoring extra entries in maps when serializing maps as records.  Code later in the writing process performs a similar check for whatever concrete (non-union) schema is actually being used.

What's the issue you've run into which motivated this change?

**Comment by stefanbacon** [comment]
I'm trying to validate user data with an avro schema
I'm looking into the java API to see how the validation is done when datum is appended to datafilewriter

**Pull request closed without merging**
